apiVersion: v1
kind: Service

metadata:
  name: server-prometheus
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '3000'
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 9090
    protocol: TCP
    name: http