# MetalLB setup
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
- github.com/metallb/metallb/config/native?ref=v0.13.10
- resources/l2-ip.l2advertisement.yaml
- resources/default-pool.ipaddresspool.yaml