apiVersion: v1
kind: Service

metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9205"
  name: server-apache-nextcloud
spec:
  type: LoadBalancer
  clusterIP: 10.43.100.3
  loadBalancerIP: 192.168.0.42
  ports:
  - port: 443
    protocol: TCP
    name: apache
  - port: 9205
    protocol: TCP
    name: metrics