apiVersion: v1
kind: Service

metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
  name: db-mariadb
spec:
  type: ClusterIP
  clusterIP: 10.43.100.2
  ports:
  - port: 3306
    protocol: TCP
    name: server
  - port: 9104
    protocol: TCP
    name: metrics